version: 0.2
phases:
  pre_build:
    commands:
      - echo "At pre-build stage..."
  build:
    commands:
      - echo "At build stage..."
      - mvn -DskipTests clean prepare-package war:exploded
  post_build:
    commands:
      - echo "At post-build stage..."
artifacts:
  files:
    - target/*.war